services:
  db:
    image: postgres:18.3-alpine3.23
    container_name: quiz_forge_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=quizForge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    driver: local
