spring:
  datasource:
    url: jdbc:tc:postgresql:18.3:///ai_project
    username: ai_user
    password: ai_password
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: validate

