spring:
  ai:
    openai:
      chat:
        base-url: http://localhost:1234
        options:
          model: google/gemma-4-e2b
      api-key: "local-llm-no-key-needed"
  datasource:
    url: jdbc:tc:postgresql:18.3:///ai_project
    username: ai_user
    password: ai_password
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: validate
