spring:
  application:
    name: quiz-forge-ai
  ai:
    openai:
      chat:
        base-url: http://localhost:11434
        options:
          model: qwen3:8b
      api-key: "your-api-key"
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_project
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG