spring:
  application:
    name: quiz-forge-ai
  ai:
    openai:
      chat:
        base-url: http://localhost:11434
        options:
          model: qwen3:8b
      api-key: "your-api-key"
  datasource:
    url: jdbc:postgresql://localhost:5432/quizForge
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
