package ai.quiz.forge.service.mapper

import ai.quiz.forge.service.model.Question
import ai.quiz.forge.service.model.Quiz
import ai.quiz.forge.service.model.ai.generated.NewQuiz

/**
 * Maps an AI-generated [NewQuiz] into the service [Quiz] domain model.
 *
 * Notes:
 * - [Quiz.id] is generated by default (UUID) and is used as the persistence key.
 * - Any selected answers coming from the AI output are ignored (we always start unanswered).
 */
object NewQuizToQuizMapper : (String, NewQuiz) -> Quiz {
    override fun invoke(topic: String, newQuiz: NewQuiz): Quiz {
        require(newQuiz.questions.isNotEmpty()) { "Quiz must contain at least one question" }

        val questions =  newQuiz.questions.map {
            Question(
                question = it.question,
                optionA = it.optionA,
                optionB = it.optionB,
                optionC = it.optionC,
                optionD = it.optionD,
                hint = it.hint,
            )
        }

        return Quiz(
            topic = topic,
            questions = questions,
        )
    }
}

