package ai.quiz.forge.service.mapper

import ai.quiz.forge.service.model.Question
import ai.quiz.forge.service.model.Quiz
import ai.quiz.forge.service.model.ai.generated.NewQuestion
import ai.quiz.forge.shared.Option

/**
 * Maps an AI-generated [NewQuiz] into the service [Quiz] domain model.
 *
 * Notes:
 * - [Quiz.id] is generated by default (UUID) and is used as the persistence key.
 * - Any selected answers coming from the AI output are ignored (we always start unanswered).
 */
object NewQuizToQuizMapper : (String, Map<NewQuestion, Option>) -> Quiz {
    override fun invoke(topic: String, questionAnswer: Map<NewQuestion, Option>): Quiz {
        require(questionAnswer.isNotEmpty()) { "Quiz must contain at least one question" }

        val questions = questionAnswer.map { (q, correctOption) ->
            // Ensure selectedOption starts empty even if AI output contains it.
            Question(
                question = q.question,
                optionA = q.optionA,
                optionB = q.optionB,
                optionC = q.optionC,
                optionD = q.optionD,
                correctOption = correctOption,
                selectedOption = null,
                hint = q.hint,
            )
        }

        return Quiz(
            topic = topic,
            questions = questions,
        )
    }
}

