package ai.quiz.forge.service.mapper

import ai.quiz.forge.service.model.Question
import ai.quiz.forge.service.model.Quiz
import ai.quiz.forge.service.model.ai.generated.NewQuiz

/**
 * Maps an AI-generated [NewQuiz] into the service [Quiz] domain model.
 *
 * Notes:
 * - [Quiz.id] is generated by default (UUID) and is used as the persistence key.
 * - Any selected answers coming from the AI output are ignored (we always start unanswered).
 */
object NewQuizToQuizMapper : (NewQuiz) -> Quiz {
    override fun invoke(newQuiz: NewQuiz): Quiz {
        require(newQuiz.questions.isNotEmpty()) { "Quiz must contain at least one question" }

        val questions = newQuiz.questions.map { q ->
            // Ensure selectedOption starts empty even if AI output contains it.
            Question(
                question = q.question,
                optionA = q.optionA,
                optionB = q.optionB,
                optionC = q.optionC,
                optionD = q.optionD,
                correctOption = q.correctOption,
                selectedOption = null,
                hint = q.hint,
            )
        }

        return Quiz(
            topic = newQuiz.topic,
            questions = questions,
        )
    }
}

