package ai.quiz.forge.service

import ai.quiz.forge.persistence.repository.QuizRepository
import ai.quiz.forge.service.mapper.QuizEntityToQuizMapper
import ai.quiz.forge.service.mapper.QuizToQuizEntityMapper
import ai.quiz.forge.service.model.Quiz
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.util.UUID

@Service
class QuizPersistenceService(
    private val quizRepository: QuizRepository,
) {
    @Transactional
    fun save(quiz: Quiz): UUID {
        val quizEntity = QuizToQuizEntityMapper(quiz)
        val saved = quizRepository.save(quizEntity)
        return requireNotNull(saved.id) { "Quiz id should be generated by the database" }
    }

    @Transactional(readOnly = true)
    fun findById(id: UUID): Quiz? {
        val entity = quizRepository.findWithQuestionsById(id) ?: return null
        return QuizEntityToQuizMapper(entity)
    }
}
