package ai.quiz.forge.service

import ai.quiz.forge.persistence.entity.QuestionEntity
import ai.quiz.forge.persistence.entity.QuizEntity
import ai.quiz.forge.persistence.repository.QuizRepository
import ai.quiz.forge.service.model.Question
import ai.quiz.forge.service.model.Quiz
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.time.OffsetDateTime
import java.util.UUID

@Service
class QuizPersistenceService(
    private val quizRepository: QuizRepository,
) {
    @Transactional
    fun save(quiz: Quiz): UUID {
        val quizEntity = QuizEntity(
            topic = quiz.topic,
            createdAt = OffsetDateTime.now(),
        )

        quiz.questions.forEachIndexed { index, q ->
            quizEntity.questions.add(
                QuestionEntity(
                    quiz = quizEntity,
                    question = q.question,
                    optionA = q.optionA,
                    optionB = q.optionB,
                    optionC = q.optionC,
                    optionD = q.optionD,
                    correctAnswer = q.correctAnswer.toEntityEnum(),
                    hint = q.hint,
                    position = index,
                )
            )
        }

        val saved = quizRepository.save(quizEntity)
        return requireNotNull(saved.id) { "Quiz id should be generated by the database" }
    }

    @Transactional(readOnly = true)
    fun findById(id: UUID): Quiz? {
        val entity = quizRepository.findWithQuestionsById(id) ?: return null
        val questions = entity.questions
            .sortedBy { it.position }
            .map {
                Question(
                    question = it.question,
                    optionA = it.optionA,
                    optionB = it.optionB,
                    optionC = it.optionC,
                    optionD = it.optionD,
                    correctAnswer = it.correctAnswer.toModelEnum(),
                    hint = it.hint,
                )
            }
        return Quiz(topic = entity.topic, questions = questions)
    }

    private fun Question.CorrectAnswer.toEntityEnum(): QuestionEntity.CorrectAnswer =
        when (this) {
            Question.CorrectAnswer.OPTION_A -> QuestionEntity.CorrectAnswer.OPTION_A
            Question.CorrectAnswer.OPTION_B -> QuestionEntity.CorrectAnswer.OPTION_B
            Question.CorrectAnswer.OPTION_C -> QuestionEntity.CorrectAnswer.OPTION_C
            Question.CorrectAnswer.OPTION_D -> QuestionEntity.CorrectAnswer.OPTION_D
        }

    private fun QuestionEntity.CorrectAnswer.toModelEnum(): Question.CorrectAnswer =
        when (this) {
            QuestionEntity.CorrectAnswer.OPTION_A -> Question.CorrectAnswer.OPTION_A
            QuestionEntity.CorrectAnswer.OPTION_B -> Question.CorrectAnswer.OPTION_B
            QuestionEntity.CorrectAnswer.OPTION_C -> Question.CorrectAnswer.OPTION_C
            QuestionEntity.CorrectAnswer.OPTION_D -> Question.CorrectAnswer.OPTION_D
        }
}
